import os
import time
import requests
import pandas as pd
import statistics

from datetime import datetime

# ==========================================================
# Configuration
# ==========================================================

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")

headers = {
    "Accept": "application/vnd.github+json"
}

if GITHUB_TOKEN:
    headers["Authorization"] = f"Bearer {GITHUB_TOKEN}"

input_csv = "./data/demographics/ros_repository_github_bottom10_others.csv"

commits_output_csv = "./data/popularity/github_commits.csv"
issues_output_csv = "./data/popularity/github_issues.csv"
prs_output_csv = "./data/popularity/github_pull_requests.csv"
ai_summary_output_csv = "./data/popularity/github_ai_summary.csv"

COMMITS_PER_REPO = 10000   # 🔥 limit to avoid API explosion
ISSUES_PER_REPO = 5000
PRS_PER_REPO = 5000

# ==========================================================
# AI Detection Configuration
# ==========================================================

AI_KEYWORDS = [
    "copilot", "chatgpt", "gpt", "claude", "cursor",
    "codex", "devin", "codeium", "tabnine",
    "llm", "ai-assisted", "generated by ai",
    "co-authored-by", "auto-generated", "openai", "gemini"
]

AI_BOT_HINTS = ["copilot", "claude", "cursor", "gpt", "chatgpt", "bot", "ai"]

# ==========================================================
# Helper Functions
# ==========================================================

def safe_request(url, params=None, timeout=30, retries=3):
    for attempt in range(retries):
        try:
            response = requests.get(url, headers=headers, params=params, timeout=timeout)

            if response.status_code == 200:
                return response

            if response.status_code in [403, 429]:
                reset = response.headers.get("X-RateLimit-Reset")
                if reset:
                    sleep_time = max(int(reset) - int(time.time()) + 5, 5)
                    print(f"Rate limit hit. Sleeping {sleep_time}s...")
                    time.sleep(sleep_time)
                    continue

            print(f"Request failed ({response.status_code}): {url}")
            return None

        except requests.exceptions.Timeout:
            print(f"Timeout... retry {attempt+1}/{retries}")
            time.sleep(5)

    return None


def extract_owner_repo(url):
    if pd.isna(url):
        return None, None

    parts = str(url).split("github.com/")[-1].split("/")
    if len(parts) < 2:
        return None, None

    return parts[0], parts[1].replace(".git", "")


# ==========================================================
# Commit Processing
# ==========================================================

def get_commits(owner, repo):
    commits = []
    page = 1

    while len(commits) < COMMITS_PER_REPO:
        url = f"https://api.github.com/repos/{owner}/{repo}/commits"
        params = {"per_page": 100, "page": page}

        response = safe_request(url, params=params)
        if not response:
            break

        batch = response.json()
        if not batch:
            break

        commits.extend(batch)
        print(f"{owner}/{repo}: {len(commits)} commits")

        if len(batch) < 100:
            break

        page += 1

    return commits[:COMMITS_PER_REPO]


def get_commit_details(owner, repo, sha):
    url = f"https://api.github.com/repos/{owner}/{repo}/commits/{sha}"
    response = safe_request(url)

    if response:
        return response.json()

    return None


def extract_commit_stats(data):
    code_ext = {".py",".cpp",".c",".h",".java",".js",".ts",".cs",".go",".rs"}

    additions = deletions = total = 0
    file_changes = []

    for f in data.get("files", []):
        ext = os.path.splitext(f.get("filename",""))[1]
        if f.get("status") == "modified" and ext in code_ext:
            additions += f.get("additions",0)
            deletions += f.get("deletions",0)
            total += f.get("changes",0)
            file_changes.append(f.get("changes",0))

    avg = sum(file_changes)/len(file_changes) if file_changes else 0
    median = statistics.median(file_changes) if file_changes else 0

    return additions, deletions, total, avg, median


def detect_ai(data, message, author):
    score = 0
    reasons = []
    tools = set()

    text = (message or "").lower()
    author = (author or "").lower()

    # keywords
    for k in AI_KEYWORDS:
        if k in text:
            score += 5
            reasons.append(f"keyword:{k}")

    # author hints
    for hint in AI_BOT_HINTS:
        if hint in author:
            score += 4
            reasons.append(f"ai_author:{author}")
            break

    # API author type
    author_data = data.get("author")
    if author_data and author_data.get("type") == "Bot":
        score += 2
        reasons.append("bot_author")

    return {
        "ai_score": score,
        "ai_detected": score > 0,
        "ai_reasons": ";".join(set(reasons)),
        "ai_tools": ""
    }


# ==========================================================
# Issues / PRs
# ==========================================================

def get_items(owner, repo, endpoint, limit):
    items = []
    page = 1

    while len(items) < limit:
        url = f"https://api.github.com/repos/{owner}/{repo}/{endpoint}"
        params = {"per_page": 100, "page": page, "state": "all"}

        response = safe_request(url, params=params)
        if not response:
            break

        batch = response.json()
        if not batch:
            break

        items.extend(batch)

        if len(batch) < 100:
            break

        page += 1

    return items[:limit]


# ==========================================================
# MAIN
# ==========================================================

df = pd.read_csv(input_csv)

commit_rows = []
issue_rows = []
pr_rows = []
summary_rows = []

for i, row in df.iterrows():
    owner, repo = extract_owner_repo(row.get("URL"))

    if not owner:
        continue

    print(f"\nProcessing {owner}/{repo}")

    commits = get_commits(owner, repo)

    repo_ai = []

    for c in commits:
        sha = c["sha"]
        commit_data = c["commit"]

        title = commit_data["message"].split("\n")[0]
        message = commit_data["message"]

        author = (
            c.get("author", {}).get("login")
            if c.get("author")
            else commit_data.get("author", {}).get("name")
        )

        full = get_commit_details(owner, repo, sha)
        if not full:
            continue

        stats = extract_commit_stats(full)
        ai = detect_ai(full, message, author)

        row_data = {
            "repository": f"{owner}/{repo}",
            "commit_sha": sha,
            "commit_date": commit_data["author"]["date"],
            "commit_title": title,
            "commit_message": message,
            "commit_author": author,
            "additions": stats[0],
            "deletions": stats[1],
            "total_changes": stats[2],
            "avg_file_changes": stats[3],
            "median_file_changes": stats[4],
            **ai
        }

        commit_rows.append(row_data)

        if ai["ai_detected"]:
            repo_ai.append(row_data)

    # repo summary
    summary_rows.append({
        "repository": f"{owner}/{repo}",
        "ai_detected": len(repo_ai) > 0,
        "total_ai_related_commits": len(repo_ai)
    })

    # issues / PRs
    issues = get_items(owner, repo, "issues", ISSUES_PER_REPO)
    prs = get_items(owner, repo, "pulls", PRS_PER_REPO)

    for issue in issues:
        if "pull_request" in issue:
            continue

        issue_rows.append({
            "repository": f"{owner}/{repo}",
            "issue_number": issue["number"],
            "issue_state": issue["state"]
        })

    for pr in prs:
        pr_rows.append({
            "repository": f"{owner}/{repo}",
            "pr_number": pr["number"],
            "pr_state": pr["state"]
        })

# ==========================================================
# SAVE
# ==========================================================

pd.DataFrame(commit_rows).to_csv(commits_output_csv, index=False)
pd.DataFrame(issue_rows).to_csv(issues_output_csv, index=False)
pd.DataFrame(pr_rows).to_csv(prs_output_csv, index=False)
pd.DataFrame(summary_rows).to_csv(ai_summary_output_csv, index=False)

print("\nDone!")