import os
import time
import requests
import pandas as pd

from datetime import datetime

import statistics


# ==========================================================
# Configuration
# ==========================================================

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")

headers = {
    "Accept": "application/vnd.github+json"
}

if GITHUB_TOKEN:
    headers["Authorization"] = f"Bearer {GITHUB_TOKEN}"

# input_csv = "ros_repository_github.csv"
input_csv = "./data/demographics/ros_repository_github_top10.csv"
# output_csv = "github_repository_activity.csv"
commits_output_csv = "./data/popularity/github_commits.csv"
issues_output_csv = "./data/popularity/github_issues.csv"
prs_output_csv = "./data/popularity/github_pull_requests.csv"

COMMITS_PER_REPO = 100
ISSUES_PER_REPO = 100
PRS_PER_REPO = 100

# ==========================================================
# AI Detection Configuration
# ==========================================================

AI_KEYWORDS = [
    "copilot",
    "github copilot",
    "chatgpt",
    "gpt",
    "gpt-3",
    "gpt-4",
    "gpt-4o",
    "claude",
    "anthropic",
    "cursor",
    "codex",
    "devin",
    "codeium",
    "tabnine",
    "amazon q",
    "llm",
    "ai-assisted",
    "generated by ai",
    "generated with ai",
    "generated using ai",
    "generated with copilot",
    "generated by copilot",
    "co-authored-by",
    "auto-generated",
    "generated tests",
    "ai generated",
    "openai",
    "gemini"
]

AI_FILE_HINTS = [
    ".cursor/",
    ".claude/",
    "agents.md",
    ".github/copilot-instructions.md",
    "copilot.yml",
    "devin.yaml",
    ".github/workflows/copilot",
    ".github/workflows/claude",
    ".github/workflows/ai",
    "prompt.md",
    "prompts/"
]

AI_BOT_HINTS = [
    "copilot",
    "claude",
    "cursor",
    "gpt",
    "chatgpt",
    "codeium",
    "tabnine",
    "devin",
    "ai",
    "bot"
]

# Optional extra CSV for repository-level AI summary
ai_summary_output_csv = "./data/popularity/github_ai_summary.csv"

# ==========================================================
# Helper Functions
# ==========================================================

def get_commit_ai_signals(owner, repo, sha, commit_message, commit_author):
    url = f"https://api.github.com/repos/{owner}/{repo}/commits/{sha}"
    response = safe_request(url)

    if not response:
        return {
            "ai_score": 0,
            "ai_detected": False,
            "ai_reasons": "",
            "ai_tools": "",
            "changed_files": ""
        }

    data = response.json()

    score = 0
    reasons = []
    tools = set()

    full_text = (commit_message or "").lower()

    author_login = (commit_author or "").lower()

    changed_files = []

    for file in data.get("files", []):
        filename = file.get("filename", "")
        filename_lower = filename.lower()

        changed_files.append(filename)

        for ai_file in AI_FILE_HINTS:
            if ai_file in filename_lower:
                score += 3
                reasons.append(f"ai_file:{filename}")

                if "copilot" in ai_file:
                    tools.add("Copilot")
                elif "claude" in ai_file:
                    tools.add("Claude")
                elif "cursor" in ai_file:
                    tools.add("Cursor")
                elif "devin" in ai_file:
                    tools.add("Devin")

    for keyword in AI_KEYWORDS:
        if keyword in full_text:
            score += 5
            reasons.append(f"keyword:{keyword}")

            if "copilot" in keyword:
                tools.add("Copilot")
            elif keyword in ["claude", "anthropic"]:
                tools.add("Claude")
            elif keyword in ["gpt", "gpt-3", "gpt-4", "gpt-4o", "chatgpt", "openai"]:
                tools.add("ChatGPT")
            elif keyword == "cursor":
                tools.add("Cursor")
            elif keyword == "devin":
                tools.add("Devin")
            elif keyword == "codeium":
                tools.add("Codeium")
            elif keyword == "tabnine":
                tools.add("Tabnine")
            elif keyword == "gemini":
                tools.add("Gemini")

    author_data = data.get("author")

    if author_data:
        author_type = author_data.get("type", "")
        author_login_api = author_data.get("login", "").lower()

        if author_type == "Bot":
            score += 2
            reasons.append("bot_author")

        for hint in AI_BOT_HINTS:
            if hint in author_login_api:
                score += 4
                reasons.append(f"ai_author:{author_login_api}")

                if "copilot" in author_login_api:
                    tools.add("Copilot")
                elif "claude" in author_login_api:
                    tools.add("Claude")
                elif "cursor" in author_login_api:
                    tools.add("Cursor")
                elif "devin" in author_login_api:
                    tools.add("Devin")
                elif "gpt" in author_login_api or "chatgpt" in author_login_api:
                    tools.add("ChatGPT")

                break

    for hint in AI_BOT_HINTS:
        if hint in author_login:
            score += 4
            reasons.append(f"ai_author:{author_login}")
            break

    return {
        "ai_score": score,
        "ai_detected": score > 0,
        "ai_reasons": "; ".join(sorted(set(reasons))),
        "ai_tools": "; ".join(sorted(tools)),
        "changed_files": "; ".join(changed_files)
    }

def extract_owner_repo(repo_url):
    if pd.isna(repo_url):
        return None, None

    repo_url = str(repo_url).strip().rstrip("/")

    if "github.com/" not in repo_url:
        return None, None

    parts = repo_url.split("github.com/")[-1].split("/")

    if len(parts) < 2:
        return None, None

    owner = parts[0]
    repo = parts[1].replace(".git", "")

    return owner, repo


def safe_request(url, params=None, timeout=20):
    while True:
        try:
            response = requests.get(
                url,
                headers=headers,
                params=params,
                timeout=timeout
            )

            # Success
            if response.status_code == 200:
                return response

            # Rate limit reached
            if response.status_code in [403, 429]:
                remaining = response.headers.get("X-RateLimit-Remaining")
                reset_time = response.headers.get("X-RateLimit-Reset")

                print(f"Rate limit reached. Remaining: {remaining}, Reset: {reset_time}")

                if reset_time:
                    reset_timestamp = int(reset_time)
                    current_timestamp = int(time.time())

                    sleep_seconds = max(reset_timestamp - current_timestamp + 5, 5)

                    reset_datetime = datetime.utcfromtimestamp(reset_timestamp)

                    print(f"Sleeping for {sleep_seconds} seconds until {reset_datetime} UTC...")
                    time.sleep(sleep_seconds)
                    continue

                else:
                    print("Sleeping for 60 seconds...")
                    time.sleep(60)
                    continue

            # Other errors
            print(f"Request failed: {url} -> {response.status_code}")
            return None

        except requests.exceptions.Timeout:
            print(f"Timeout while requesting: {url}")
            return None

        except requests.exceptions.ConnectionError:
            print(f"Connection error while requesting: {url}")
            return None

        except requests.exceptions.RequestException as e:
            print(f"Request error for {url}: {e}")
            return None


def get_default_branch(owner, repo):
    url = f"https://api.github.com/repos/{owner}/{repo}"
    response = safe_request(url)

    if response:
        return response.json().get("default_branch", "main")

    return "main"


def get_repo_tree(owner, repo, branch):
    url = f"https://api.github.com/repos/{owner}/{repo}/git/trees/{branch}"
    params = {"recursive": 1}

    response = safe_request(url, params=params)

    if response:
        return response.json().get("tree", [])

    return []

def get_file_content(owner, repo, path, branch, timeout=30):
    url = f"https://raw.githubusercontent.com/{owner}/{repo}/{branch}/{path}"

    try:
        response = requests.get(
            url,
            headers=headers,
            timeout=timeout
        )

        if response.status_code == 200:
            return response.text

    except requests.exceptions.Timeout:
        print(f"Timeout downloading file: {url}")

    except requests.exceptions.RequestException as e:
        print(f"Error downloading file {url}: {e}")

    return None

def get_commits(owner, repo):
    commits = []
    page = 1
    per_page = 100

    while True:
        url = f"https://api.github.com/repos/{owner}/{repo}/commits"
        params = {
            "per_page": per_page,
            "page": page
        }

        response = safe_request(url, params=params)

        if not response:
            break

        batch = response.json()

        if not batch:
            break

        commits.extend(batch)

        print(f"Collected {len(commits)} commits from {owner}/{repo}")

        # If fewer than per_page items were returned, it was the last page
        if len(batch) < per_page:
            break

        page += 1

    return commits

def get_commit_stats(owner, repo, sha):
    url = f"https://api.github.com/repos/{owner}/{repo}/commits/{sha}"
    response = safe_request(url)

    if not response:
        return None, None, None, None, None

    data = response.json()

    code_extensions = {
        ".py", ".cpp", ".cc", ".c", ".h", ".hpp",
        ".java", ".js", ".ts", ".tsx", ".jsx",
        ".cs", ".go", ".rs", ".php", ".rb",
        ".swift", ".kt", ".scala",
        ".m", ".mm", ".sh", ".r", ".dart",
        ".lua", ".pl"
    }

    additions = 0
    deletions = 0
    total_changes = 0

    file_changes = []

    files = data.get("files", [])

    for file in files:
        filename = file.get("filename", "").lower()
        status = file.get("status", "")
        _, ext = os.path.splitext(filename)

        # Only consider modified code files
        if status == "modified" and ext in code_extensions:
            file_additions = file.get("additions", 0)
            file_deletions = file.get("deletions", 0)
            file_total = file.get("changes", 0)

            additions += file_additions
            deletions += file_deletions
            total_changes += file_total

            file_changes.append(file_total)

    if file_changes:
        avg_changes = sum(file_changes) / len(file_changes)
        median_changes = statistics.median(file_changes)
    else:
        avg_changes = 0
        median_changes = 0

    return additions, deletions, total_changes, avg_changes, median_changes


def get_issues(owner, repo, state="all"):
    issues = []
    page = 1
    per_page = 100

    while True:
        url = f"https://api.github.com/repos/{owner}/{repo}/issues"
        params = {
            "state": state,
            "per_page": per_page,
            "page": page
        }

        response = safe_request(url, params=params)

        if not response:
            break

        batch = response.json()

        if not batch:
            break

        # Remove pull requests from issues endpoint
        batch = [item for item in batch if "pull_request" not in item]

        issues.extend(batch)

        print(f"Collected {len(issues)} issues from {owner}/{repo}")

        if len(batch) < per_page:
            break

        page += 1

    return issues


def get_pull_requests(owner, repo, state="all"):
    prs = []
    page = 1
    per_page = 100

    while True:
        url = f"https://api.github.com/repos/{owner}/{repo}/pulls"
        params = {
            "state": state,
            "per_page": per_page,
            "page": page
        }

        response = safe_request(url, params=params)

        if not response:
            break

        batch = response.json()

        if not batch:
            break

        prs.extend(batch)

        print(f"Collected {len(prs)} pull requests from {owner}/{repo}")

        if len(batch) < per_page:
            break

        page += 1

    return prs


# ==========================================================
# Main Script
# ==========================================================

df = pd.read_csv(input_csv)

# rows = []

commit_rows = []
issue_rows = []
pr_rows = []
repo_ai_summary_rows = []

for index, row in df.iterrows():
    repo_url = row.get("URL")

    owner, repo = extract_owner_repo(repo_url)

    if not owner or not repo:
        print(f"Skipping invalid URL: {repo_url}")
        continue

    print(f"[{index + 1}/{len(df)}] Processing {owner}/{repo}")

    try:
        # dependencies = detect_dependencies(owner, repo)

        commits = get_commits(owner, repo)
        issues = get_issues(owner, repo, state="all")
        pull_requests = get_pull_requests(owner, repo, state="all")

        # ==========================================================
        # Save Commits
        # ==========================================================

        for commit in commits:
            commit_data = commit.get("commit", {})

            commit_date = None
            if commit_data.get("author"):
                commit_date = commit_data["author"].get("date")

            full_message = commit_data.get("message", "")
            title = full_message.split("\n")[0] if full_message else ""
            message = "\n".join(full_message.split("\n")[1:]).strip()

            author_name = None
            if commit.get("author"):
                author_name = commit["author"].get("login")
            elif commit_data.get("author"):
                author_name = commit_data["author"].get("name")

            sha = commit.get("sha")
            additions, deletions, total_changes, avg_changes, median_changes = get_commit_stats(owner, repo, sha)

            additions, deletions, total_changes, avg_changes, median_changes = get_commit_stats(owner, repo, sha)

            full_commit_text = f"{title}\n{message}"

            ai_data = get_commit_ai_signals(
                owner,
                repo,
                sha,
                full_commit_text,
                author_name
            )

            commit_rows.append({
                "repository": f"{owner}/{repo}",
                "commit_sha": sha,
                "commit_date": commit_date,
                "commit_title": title,
                "commit_message": message,
                "commit_author": author_name,
                "additions": additions,
                "deletions": deletions,
                "total_changes": total_changes,
                "avg_file_changes": avg_changes,
                "median_file_changes": median_changes,
                "ai_detected": ai_data["ai_detected"],
                "ai_score": ai_data["ai_score"],
                "ai_reasons": ai_data["ai_reasons"],
                "ai_tools": ai_data["ai_tools"],
                "changed_files": ai_data["changed_files"]
            })

            repo_commit_rows = [
                row for row in commit_rows
                if row["repository"] == f"{owner}/{repo}"
            ]

            repo_ai_commits = [
                row for row in repo_commit_rows
                if row["ai_detected"]
            ]

            if repo_ai_commits:
                repo_ai_commits = sorted(
                    repo_ai_commits,
                    key=lambda x: x["commit_date"] if x["commit_date"] else ""
                )

                first_ai_commit = repo_ai_commits[0]

                all_tools = sorted(set(
                    tool.strip()
                    for row in repo_ai_commits
                    for tool in row["ai_tools"].split(";")
                    if tool.strip()
                ))

                max_score = max(row["ai_score"] for row in repo_ai_commits)

                if max_score >= 10:
                    confidence = "strong"
                elif max_score >= 5:
                    confidence = "moderate"
                else:
                    confidence = "weak"

                repo_ai_summary_rows.append({
                    "repository": f"{owner}/{repo}",
                    "ai_detected": True,
                    "confidence": confidence,
                    "first_ai_commit_sha": first_ai_commit["commit_sha"],
                    "first_ai_commit_date": first_ai_commit["commit_date"],
                    "first_ai_commit_title": first_ai_commit["commit_title"],
                    "total_ai_related_commits": len(repo_ai_commits),
                    "max_ai_score": max_score,
                    "possible_ai_tools": "; ".join(all_tools)
                })

            else:
                repo_ai_summary_rows.append({
                    "repository": f"{owner}/{repo}",
                    "ai_detected": False,
                    "confidence": "none",
                    "first_ai_commit_sha": None,
                    "first_ai_commit_date": None,
                    "first_ai_commit_title": None,
                    "total_ai_related_commits": 0,
                    "max_ai_score": 0,
                    "possible_ai_tools": ""
                })

        # ==========================================================
        # Save Issues
        # ==========================================================

        for issue in issues:

            issue_rows.append({
                "repository": f"{owner}/{repo}",
                "issue_number": issue.get("number"),
                "issue_state": issue.get("state"),
                "issue_title": issue.get("title"),
                "issue_created_at": issue.get("created_at"),
                "issue_closed_at": issue.get("closed_at"),
                "issue_author": issue.get("user", {}).get("login"),
                "issue_comments": issue.get("comments")
            })

        # ==========================================================
        # Save Pull Requests
        # ==========================================================

        for pr in pull_requests:
            pr_rows.append({
                "repository": f"{owner}/{repo}",
                "pr_number": pr.get("number"),
                "pr_state": pr.get("state"),
                "pr_title": pr.get("title"),
                "pr_created_at": pr.get("created_at"),
                "pr_closed_at": pr.get("closed_at"),
                "pr_merged_at": pr.get("merged_at"),
                "pr_author": pr.get("user", {}).get("login"),
                "pr_comments": pr.get("comments")
            })

        time.sleep(0.5)

    except Exception as e:
        print(f"Error processing {owner}/{repo}: {e}")

# ==========================================================
# Save Results
# ==========================================================

commit_columns = [
    "repository",
    "commit_sha",
    "commit_date",
    "commit_title",
    "commit_message",
    "commit_author",
    "additions",
    "deletions",
    "total_changes",
    "avg_file_changes",
    "median_file_changes",
    "ai_detected",
    "ai_score",
    "ai_reasons",
    "ai_tools",
    "changed_files"
]

issue_columns = [
    "repository",
    "issue_number",
    "issue_state",
    "issue_title",
    "issue_created_at",
    "issue_closed_at",
    "issue_author",
    "issue_comments"
]

pr_columns = [
    "repository",
    "pr_number",
    "pr_state",
    "pr_title",
    "pr_created_at",
    "pr_closed_at",
    "pr_merged_at",
    "pr_author",
    "pr_comments"
]

repo_ai_summary_columns = [
    "repository",
    "ai_detected",
    "confidence",
    "first_ai_commit_sha",
    "first_ai_commit_date",
    "first_ai_commit_title",
    "total_ai_related_commits",
    "max_ai_score",
    "possible_ai_tools"
]

repo_ai_summary_df = pd.DataFrame(
    repo_ai_summary_rows,
    columns=repo_ai_summary_columns
)

repo_ai_summary_df.to_csv(ai_summary_output_csv, index=False)

print(f"Saved AI summary to {ai_summary_output_csv}")

commit_df = pd.DataFrame(commit_rows, columns=commit_columns)
issue_df = pd.DataFrame(issue_rows, columns=issue_columns)
pr_df = pd.DataFrame(pr_rows, columns=pr_columns)

commit_df.to_csv(commits_output_csv, index=False)
issue_df.to_csv(issues_output_csv, index=False)
pr_df.to_csv(prs_output_csv, index=False)

print(f"Saved commits to {commits_output_csv}")
print(f"Saved issues to {issues_output_csv}")
print(f"Saved pull requests to {prs_output_csv}")